# Generated by Django 5.2.14 on 2026-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
